/* ================= MY LEARNING WORLD — SEED DATA =================
   Media model: m.media = {type:'youtube', youtubeId, channel} or {type:'mock'}.
   Provenance: 'verified-transcript' | 'retrieved-description' | 'mock-script' | 'demo'.
   'verified-transcript' = checked against the actual video's verbatim transcript.
   Never present anything else as transcript-derived. */
const ZONES = [
  {id:'home', name:"Jackson's Home", emoji:'🏠', x:400, y:330, desc:'Home base'},
  {id:'minecraft', name:'Block Builders', emoji:'⛏️', x:180, y:220, desc:'Building & making'},
  {id:'dino', name:'Dino Valley', emoji:'🦕', x:150, y:430, desc:'Dinosaurs & fossils'},
  {id:'space', name:'Space Port', emoji:'🚀', x:400, y:110, desc:'Space & planets'},
  {id:'engineering', name:'Engineering Canyon', emoji:'🌉', x:620, y:220, desc:'Bridges & machines'},
  {id:'earth', name:'Earth Depths', emoji:'🌋', x:250, y:560, desc:'Volcanoes & rocks'},
  {id:'history', name:'Ancient Echoes', emoji:'🏛️', x:600, y:450, desc:'Rome & the past'},
  {id:'ocean', name:'Deep Ocean', emoji:'🦈', x:430, y:660, desc:'Sharks & seas'},
];
const ZONE_GRAD = {
  home:'linear-gradient(135deg,#a78bfa,#6d28d9)', minecraft:'linear-gradient(135deg,#86efac,#15803d)',
  dino:'linear-gradient(135deg,#fde68a,#d97706)', space:'linear-gradient(135deg,#1e1b4b,#7c3aed)',
  engineering:'linear-gradient(135deg,#fdba74,#c2410c)', earth:'linear-gradient(135deg,#fca5a5,#b91c1c)',
  history:'linear-gradient(135deg,#fcd34d,#92400e)', ocean:'linear-gradient(135deg,#7dd3fc,#0c4a6e)'
};

const MISSIONS = [
{id:'volcano', title:'Why Do Volcanoes Erupt?', theme:'earth', zone:'earth', type:'discovery',
  emoji:'🌋', grad:'linear-gradient(135deg,#fca5a5,#b91c1c)', duration:'12 min', xp:150, coins:40,
  collectible:{name:'Lava Rock', emoji:'🪨'}, worldItem:{name:'Volcano Biome', emoji:'🌋'},
  desc:'Journey to the center of the Earth to discover what makes mountains explode!',
  skills:['Science','Geography','Critical Thinking'], tags:['Dinosaurs','Engineering','Geology'],
  source:{type:'video', videoId:'K7Oq9_DU1Mc', provenance:'verified-transcript', transcriptNote:'Full verbatim transcript verified 2026-09-04: Stromboli erupting 2,000 years, magma pocket → lava naming, vent/crater, fountain vs ooze, Mauna Loa tallest, Hawaii built underwater. No pressure/gas eruption-cause explanation.'},
  media:{type:'youtube', youtubeId:'K7Oq9_DU1Mc', channel:'SciShow Kids'},
  predict:{type:'choice', q:'Squeeze a toothpaste tube with the cap barely open… what happens? What do YOU think happens inside a volcano before it erupts?',
    options:['It explodes out all at once!','It oozes out slowly','Nothing — it just sits there']},
  triggers:[{at:60, prompt:'Pause! Pressure is building under the volcano RIGHT NOW. What happens first — slow ooze or giant BOOM?', options:['Slow ooze 🌋','Giant BOOM 💥','It takes a nap 😴']}],
  video:{title:'All About Volcanoes: How They Form, Eruptions & More! — SciShow Kids', duration:'3:05', chapters:['Stromboli the lighthouse','Magma pocket','Vent & crater','Fountain vs ooze'],
    script:'Stromboli has erupted for 2,000 years! Deep inside Earth rock melts into magma; when it breaks through to the air it is called lava. Lava cools into rock layers that build the mountain — through a tube called the vent, out the top called the crater.'},
  questions:[
    {kind:'mc', q:'What is melted rock UNDER the ground called?', options:['Lava','Magma','Ash','Smoke'], answer:1, why:'Underground = magma. Once it breaks through to the air it gets a new name: lava!', source:'video', sourceConcept:'magma vs lava', sourceProvenance:'verified-transcript', sourceExcerpt:'Verbatim: “It’s so hot that the rock… is actually melted! It’s called magma… if the magma breaks through all the way to the surface and reaches the air, it’s called lava.”'},
    {kind:'tf', q:'True or false: Lava and magma are exactly the same thing in the same place.', options:['True','False'], answer:1, why:'False! Same melted rock, different place. Underground = magma, outside = lava.', source:'video', sourceConcept:'magma vs lava', sourceProvenance:'verified-transcript', sourceExcerpt:'Verbatim: magma beneath the surface; called lava once it “reaches the air.”'},
    {kind:'sort', q:'How does a volcano mountain grow? Put it in order:', options:['Lava erupts from the crater','Lava cools into a rock layer','Layers pile up into a mountain'], answer:[0,1,2], why:'Erupt, cool, pile up — layer by layer, the mountain grows!', source:'video', sourceConcept:'mountain growth', sourceProvenance:'verified-transcript', sourceExcerpt:'Verbatim: “Soon the lava cools down and creates a layer of rock. Over time, many layers build up… to form the mountain.”'},
    {kind:'img', q:'Stromboli shoots lava like a fiery fountain. Which picture shows lava?', options:[{e:'🌊',t:'Ocean wave'},{e:'🔥',t:'Glowing red lava'},{e:'❄️',t:'Snow'},{e:'🌪️',t:'Tornado'}], answer:1, why:'Lava is bright red and very hot when it first erupts!', source:'video', sourceConcept:'lava appearance', sourceProvenance:'verified-transcript', sourceExcerpt:'Verbatim: “Lava is bright red and very hot when it first erupts out of the ground.”'},
    {kind:'short', q:'Hawaii’s islands are volcanoes that started UNDERWATER. How did they become islands?', keywords:['lava','layers','pile','build','grow','ocean','surface','cool'], why:'Exactly! Layer after layer of oozed lava piled up for millions of years until it rose above the waves!', source:'video', sourceConcept:'Hawaii formation', sourceProvenance:'verified-transcript', sourceExcerpt:'Verbatim: “All of the islands of Hawaii are made of volcanoes that began underwater… all of the layers of lava… built up, until they reached above the surface of the ocean.”'}
  ],
  creative:{title:'Design a volcano-proof Minecraft base!', prompt:'Volcanic ash is falling near your Minecraft village. Design a base that could survive. Where would you build it? What blocks would you use?', tabs:['text','draw','build'],
    scout:'Great thinking! Building higher helps protect the base from lava flows. You also chose strong blocks — much smarter than wood near heat.'},
  rabbitHoles:[
    {to:'supervolcano', why:'Some volcanoes are unimaginably larger…', bridge:'That eruption was big — but some volcanoes are a THOUSAND times bigger. No mountain at all. Just a dent the size of a city.'},
    {to:'pompeii', why:'Volcanoes can destroy entire cities…', bridge:'Ash doesn’t just cover hillsides. Once, it froze a whole Roman city in a single day — breakfast still on the tables.'},
    {to:'islands', why:'Volcanoes can actually CREATE new land…', bridge:"Volcanoes don't only destroy land — sometimes they CREATE it. That's how some islands were born."},
    {to:'mars', why:'The biggest volcano is NOT on Earth', bridge:'Earth’s biggest volcano is impressive. But Mars hides one THREE times taller than Everest. Pack something warm.'}]},
{id:'jets', title:'How Do Fighter Jets Fly?', theme:'engineering', zone:'engineering', type:'discovery',
  emoji:'🛩️', grad:'linear-gradient(135deg,#7dd3fc,#1d4ed8)', duration:'11 min', xp:140, coins:35,
  collectible:{name:'Mini Jet Engine', emoji:'🌀'}, worldItem:{name:'Wind Tunnel Lab', emoji:'🏭'},
  desc:'Strap in! Discover the invisible force called lift that holds jets in the sky.',
  skills:['Science','Math','Critical Thinking'], tags:['Fighter Jets','Engineering','Cars'],
  source:{type:'video', videoId:'VLpSxHwfU04', provenance:'retrieved-description', transcriptNote:'Publisher description + corroborating summaries verified 2026-09-04: thrust moves plane forward, wing shape creates lift. Full transcript not retrievable (caption download blocked); questions limited to description-supported claims.'},
  media:{type:'youtube', youtubeId:'VLpSxHwfU04', channel:'SciShow Kids'},
  predict:{type:'choice', q:'A fighter jet weighs as much as 10 cars. How could ANYTHING that heavy float in the sky?',
    options:['Its wings push air down','Giant invisible hands hold it','Super-strong magic engines','It never really flies']},
  video:{title:'How Airplanes Fly! — SciShow Kids', duration:'4:30', chapters:['Heavy but floating','Wings bend air','Lift vs gravity','Engines & thrust'],
    script:'Squeaks is scared to fly! Jessi shows how thrust from engines moves the plane forward while the special wing shape creates lift that holds it up. Wings, lift, air pressure, engines, thrust — the recipe for flight.'},
  questions:[
    {kind:'mc', q:'What is the upward push on a wing called?', options:['Thrust','Gravity','Lift','Drag'], answer:2, why:'Lift! The wing shape creates lift that holds the plane up.', source:'video', sourceConcept:'lift', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description + tags: wings, wing, lift, air pressure, engine, thrust; “the unique shape of the wings creates lift.”'},
    {kind:'tf', q:'True or false: Engines hold the plane up; wings just steer.', options:['True','False'], answer:1, why:'False! Engines push forward (thrust). Wings make lift — that is what holds it up.', source:'video', sourceConcept:'thrust vs lift', sourceProvenance:'retrieved-description', sourceExcerpt:'Corroborated summary: thrust moves the airplane forward; wing shape creates lift.'},
    {kind:'mc', q:'What pushes a plane FORWARD?', options:['Lift','Thrust from the engines','Gravity','Wind'], answer:1, why:'Thrust! Engines move the plane forward — then the wings can make lift.', source:'video', sourceConcept:'thrust', sourceProvenance:'retrieved-description', sourceExcerpt:'Corroborated summary: “thrust from the engines moves the airplane forward.”'},
    {kind:'short', q:'Explain lift to a friend in one or two sentences.', keywords:['air','wing','push','up','bend','lift'], why:'Perfect! Special wing shape + moving air = lift!', source:'general', sourceConcept:'explain lift', sourceProvenance:'retrieved-description', sourceExcerpt:'Child explains the video’s core idea in own words (evaluative, no new facts).'}
  ],
  creative:{title:'Explain how a jet flies', prompt:'Pretend your little cousin asks: how does a giant heavy jet stay in the sky? Explain it your way — words, a drawing, or both!', tabs:['text','draw','voice'],
    scout:'Love that explanation! You nailed the key idea: wings push air down, air pushes back up. Real engineer thinking.'},
  rabbitHoles:[
    {to:'birds', why:'Jets copied THEM first…', bridge:'Engineers didn’t invent wings — they copied them. The original flying machines are feathered, and some are dinosaurs.'},
    {to:'mars', why:'Jets need air… what flies without it?', bridge:'Jets need thick air to push on. Mars barely has any — so how would you fly THERE?'},
    {to:'car', why:'Engines that stay on the ground', bridge:'Same explosion-power, different job: what happens when an engine pushes cars instead of jets?'},
    {to:'bridges', why:'Forces are everywhere', bridge:'Lift, thrust, weight — the sky is full of forces. Bridges wrestle the same invisible forces sideways.'}]},
{id:'bridges', title:'Can You Build the Strongest Bridge?', theme:'engineering', zone:'engineering', type:'challenge',
  emoji:'🌉', grad:'linear-gradient(135deg,#fdba74,#9a3412)', duration:'10 min', xp:130, coins:35,
  collectible:{name:'Tiny Steel Beam', emoji:'🔩'}, worldItem:{name:'Suspension Bridge', emoji:'🌉'},
  desc:'Three bridge designs. One toy car. Which bridge holds the most?',
  skills:['Math','Science','Critical Thinking','Creativity'], tags:['Minecraft','Engineering','Cars'],
  source:{type:'video', videoId:'oVOnRPefcno', provenance:'verified-transcript', transcriptNote:'Verbatim transcript excerpts verified 2026-09-04: beam bridge collapses under weight, George Washington Bridge + iron/steel, shape matters beyond materials. Chapters: Trusses, Suspension Bridges.'},
  media:{type:'youtube', youtubeId:'oVOnRPefcno', channel:'SciShow Kids'},
  predict:{type:'choice', q:'A truck must cross: a flat log, a curved arch, or a triangle truss. Which one is still standing at the end?',
    options:['🟫 The flat log','🌈 The curved arch','🔺 The triangle truss']},
  video:{title:'What Makes Bridges So Strong? — SciShow Kids', duration:'3:45', chapters:['Beam vs arch vs truss','The magic triangle','Load test!'],
    script:'Engineers test three bridges: a flat beam, an arch, and a truss full of triangles. Triangles cannot squish without changing side lengths — that makes them super strong. The truss wins, holding 10x the weight!'},
  questions:[
    {kind:'img', q:'Which bridge would hold the MOST toy cars?', options:[{e:'🟫',t:'Flat log beam'},{e:'🌈',t:'Curved arch'},{e:'🔺',t:'Triangle truss'}], answer:2, why:'The triangle truss! Triangles share weight across every side — engineers use them everywhere.', source:'video', sourceConcept:'truss strength', sourceProvenance:'verified-transcript', sourceExcerpt:'Verbatim: “A beam bridge can be just a log… All bridges can hold a certain amount of weight, but what happens if we put too much weight on a beam bridge? It collapses.”'},
    {kind:'mc', q:'In the video, what is the world’s busiest bridge an example of?', options:['How much weight real bridges carry every day','A bridge made of wood','A bridge for trains only'], answer:0, why:'The George Washington Bridge carries mountains of cars and trucks daily — strength matters!', source:'video', sourceConcept:'real bridges', sourceProvenance:'verified-transcript', sourceExcerpt:'Verbatim: “Take the world’s busiest bridge, the George Washington Bridge… For a bridge to carry that much weight, it has to be built of special material, like iron and steel.”'},
    {kind:'tf', q:'True or false: Strong materials alone are enough — shape doesn’t matter.', options:['True','False'], answer:1, why:'False! The video shows it takes MORE than tough materials — shape does half the work.', source:'video', sourceConcept:'shape vs material', sourceProvenance:'verified-transcript', sourceExcerpt:'Verbatim: “But it takes more than tough materials to make a strong bridge.”'},
    {kind:'short', q:'You get 20 straws and tape. Describe your bridge design.', keywords:['triangle','truss','arch','support','beam','strong'], why:'An engineer plan! Triangles plus strong supports — that bridge will hold a LOT.', source:'general', sourceConcept:'design transfer', sourceProvenance:'curated-brief'}
  ],
  creative:{title:'Design a bridge', prompt:'Draw or describe a bridge for toy cars over a river. What shape? What materials? Why will it hold?', tabs:['draw','text','build'],
    scout:'Triangles in your design — excellent! Real bridge engineers do exactly that. You think like a builder.'},
  rabbitHoles:[
    {to:'forces', why:'The invisible push-behind every bridge', bridge:'Bridges don’t just sit there — they wrestle pushes and pulls all day. Meet the invisible forces doing the wrestling.'},
    {to:'skyscraper', why:'Bridges standing UP', bridge:'Same tricks, turned vertical: what happens when a bridge decides to stand up and touch the clouds?'},
    {to:'aqueducts', why:'Roman bridges for water', bridge:'Two thousand years ago, Romans built bridges not for roads — but for RIVERS. They carried water across valleys.'},
    {to:'mathbattle', why:'Test your math power', bridge:'Engineers calculate every beam. Sharpen your math sword for the next build.'}]},
{id:'dino', title:'Why Did Dinosaurs Disappear?', theme:'dino', zone:'dino', type:'story',
  emoji:'🦕', grad:'linear-gradient(135deg,#fde68a,#b45309)', duration:'13 min', xp:150, coins:40,
  collectible:{name:'Fossil Fragment', emoji:'🦴'}, worldItem:{name:'Dino Dig Site', emoji:'🦕'},
  desc:'You are a fossil hunter. Follow the clues from bones to an asteroid...',
  skills:['Science','History','Reading','Critical Thinking'], tags:['Dinosaurs','Geology'],
  source:{type:'video', videoId:'oXwoy-Ce1ZE', provenance:'verified-transcript', transcriptNote:'Full verbatim transcript verified 2026-09-04: asteroid 12 km wide, Chicxulub crater ~150 km, ~65M years, soot blocked sun; cause left a mystery (asteroid, volcanoes, or both).'},
  media:{type:'youtube', youtubeId:'oXwoy-Ce1ZE', channel:'SciShow Kids'},
  predict:{type:'choice', q:'The biggest animals EVER all vanished. What could possibly wipe out ALL the dinosaurs?',
    options:['☄️ A rock from space','🚚 They all moved away','🤧 One giant cold','🌋 Volcanoes only']},
  video:{title:'What Happened to the Dinosaurs? — SciShow Kids', duration:'4:39', chapters:['The mystery','Clues in the rocks','The space rock'],
    script:'Jessi, Squeaks and Dino solve a 65-million-year-old mystery: a 12-km-wide asteroid struck Mexico, leaving the 150-km Chicxulub crater. Billions of tons of soot blocked the sun, plants died — yet volcanoes may share the blame. The true culprit stays a mystery... for now.'},
  story:{start:'dig',
    nodes:{
      dig:{text:'You brush dust off a giant leg bone in the desert. Your scanner beeps: this bone is about 65 MILLION years old. Dino’s field notes mention a 12-km-wide space rock and a crater 150 km across in Mexico. A trail of soot-dark rock leads toward the hills.', choices:[{t:'🔦 Follow the soot-dark trail', to:'crater'},{t:'🪨 Examine the dusty rock first', to:'rocks'}]},
      crater:{text:'The trail climbs a huge curved ridge — like the rim of a giant bowl. From the top you see it: a dent about 150 km wide. This is no hill. This is a CRATER.', choices:[{t:'🧪 Test the soot layer', to:'layer'},{t:'🦴 Dig for fossils above the crater', to:'ending1'}]},
      rocks:{text:'The dark rock is full of SOOT — the dusty stuff left when things burn. Dino’s notes say billions of tons of it once filled the sky and blocked the sun. But some scientists blame volcanoes instead... The trail still waits.', choices:[{t:'🔦 Follow the trail now', to:'crater'},{t:'🌋 Check the volcano clues too', to:'ending2'}]},
      layer:{text:'Under your microscope: a thin dark soot line in the rock, sitting exactly where dinosaur fossils STOP. Above it: no dinosaurs — only small survivors. The sky went dark right when the giants vanished.', choices:[{t:'📢 Announce what the clues show!', to:'ending3'}]},
      ending1:{end:true, text:'Above the crater rim: no dinosaur fossils at all — only tiny mammals and small survivors. The giants are gone, but life goes on. Your discovery map is complete!'},
      ending2:{end:true, text:'You compare both suspects: a 12-km asteroid AND giant volcanoes in India erupting for a million years. Like the video says — it could be the asteroid, the volcanoes, or both! A true mystery... for now.'},
      ending3:{end:true, text:'HEADLINE: Kid scientist cracks the case WIDE OPEN — and keeps it honest! A giant asteroid, maybe volcanoes too. Some questions stay mysteries until more clues arrive. That is real science.'}
    }},
  questions:[
    {kind:'mc', q:'How wide is the Chicxulub crater in the video?', options:['15 km','150 km','1,500 km','15,000 km'], answer:1, why:'About 150 km — so big you can only see its curve from the rim!', source:'video', sourceConcept:'crater width', sourceProvenance:'verified-transcript', sourceExcerpt:'Verbatim: “It’s called the Chicxulub crater, and it’s about 150 kilometers wide.”'},
    {kind:'mc', q:'How wide was the asteroid itself?', options:['12 meters','12 kilometers','12,000 kilometers','As wide as the Moon'], answer:1, why:'12 km — so big it would take hours just to walk across!', source:'video', sourceConcept:'asteroid size', sourceProvenance:'verified-transcript', sourceExcerpt:'Verbatim: “This asteroid was enormous — it was 12 kilometers wide.”'},
    {kind:'mc', q:'What does the video say ended the dinosaurs?', options:['Definitely volcanoes only','Scientists aren’t sure — asteroid, volcanoes, or both','They all moved away','A giant cold'], answer:1, why:'The video keeps it a mystery: soot blocked the sun, but volcanoes may share the blame — maybe both!', source:'video', sourceConcept:'mystery cause', sourceProvenance:'verified-transcript', sourceExcerpt:'Verbatim: “It could have been the asteroid, or it could have been the volcanoes, or both!”'}
  ],
  creative:{title:'Draw a dinosaur habitat', prompt:'Draw or describe the world the day BEFORE the asteroid hit. What plants, dinosaurs, and weather do you see?', tabs:['draw','text','voice'],
    scout:'What an imagination! Lush plants, giant herds... and no idea what tomorrow brings. You painted the lost world beautifully.'},
  rabbitHoles:[
    {to:'fossils', why:'The bones left behind…', bridge:'The dinosaurs are gone — but they left clues in stone. One girl found sea monsters in an English cliff.'},
    {to:'volcano', why:'Another way worlds change', bridge:'Space rocks aren’t the only world-changers. Mountains that explode reshape everything too.'},
    {to:'pompeii', why:'Buried in a single day', bridge:'66 million years ago, dust buried a world. 2,000 years ago, ash buried a city. Same story, smaller stage.'}]},
{id:'skyscraper', title:"Why Don't Skyscrapers Fall Over?", theme:'engineering', zone:'engineering', type:'discovery',
  emoji:'🏙️', grad:'linear-gradient(135deg,#a5b4fc,#3730a3)', duration:'10 min', xp:130, coins:30,
  collectible:{name:'Golden Rivet', emoji:'🔩'}, worldItem:{name:'Sky Tower', emoji:'🏙️'},
  desc:'Tall as 50 houses stacked! Discover the hidden skeleton inside every tower.',
  skills:['Science','Math','Critical Thinking'], tags:['Engineering','Minecraft','Cars'],
  source:{type:'video', videoId:'nx7-tPP4ZrQ', provenance:'retrieved-description', transcriptNote:'Publisher description verified 2026-09-04: smart designs, strong materials, cool machines; special shapes and materials; foundations keep buildings standing; tallest-skyscraper facts. Full transcript not retrievable; questions limited to description-supported claims.'},
  media:{type:'youtube', youtubeId:'nx7-tPP4ZrQ', channel:'School Studies'},
  predict:{type:'choice', q:'Stack 50 houses on top of each other. The wind pushes hard. What keeps the tower from tipping over?',
    options:['Deep roots underground','It’s glued to clouds','Being very heavy on top','Luck']},
  video:{title:'How Do Engineers Build the Tallest Skyscrapers? — School Studies', duration:'4:15', chapters:['Deep roots','Smart shapes','Strong materials'],
    script:'Engineers use smart designs, strong materials, and cool machines to build super tall towers! Special shapes spread out wind and weight, and deep foundations grip the ground so 50 stacked houses never tip over.'},
  questions:[
    {kind:'mc', q:'What THREE things do engineers use to build super tall towers?', options:['Smart designs, strong materials, cool machines','Hope, luck, and paint','Taller ladders and glue'], answer:0, why:'Smart designs + strong materials + cool machines — the video’s recipe!', source:'video', sourceConcept:'engineering recipe', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: “Learn how engineers use smart designs, strong materials, and cool machines to build super tall towers.”'},
    {kind:'mc', q:'What is the job of a skyscraper’s foundation?', options:['To look pretty','To grip the ground so the tower never tips','To hold the elevators only'], answer:1, why:'Foundations grip deep underground — that is what keeps towers standing!', source:'video', sourceConcept:'foundations', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: “How foundations keep buildings from falling.”'},
    {kind:'short', q:'Why does a tower need a DEEP foundation?', keywords:['weight','support','ground','stable','anchor','wind'], why:'Exactly! All that weight (plus wind!) must be anchored deep into solid ground.', source:'general', sourceConcept:'foundation reasoning', sourceProvenance:'retrieved-description', sourceExcerpt:'Reasoning from the video’s foundation segment (evaluative, no new facts).'}
  ],
  creative:{title:'Invent a tower', prompt:'Design the tallest, coolest tower ever. How tall? What shape? How does it stand up in wind?', tabs:['draw','text','build'],
    scout:'A tower with cross-braces AND a deep foundation? You just designed a real skyscraper. Architects would hire you!'},
  rabbitHoles:[
    {to:'bridges', why:'Same tricks, sideways', bridge:'Towers are bridges standing up. Lay one on its side and span a river — same forces, new puzzle.'},
    {to:'aqueducts', why:'Ancient super-builders', bridge:'Modern towers reach for clouds. Ancient builders reached across valleys — with stone, arches, and no engines.'},
    {to:'mars', why:'Buildings on another planet', bridge:'Now imagine building tall where the ground is frozen dust and the air barely exists.'}]},
{id:'pompeii', title:'What Was Pompeii?', theme:'history', zone:'history', type:'story',
  emoji:'🏛️', grad:'linear-gradient(135deg,#fcd34d,#92400e)', duration:'14 min', xp:160, coins:45,
  collectible:{name:'Roman Coin', emoji:'🪙'}, worldItem:{name:'Roman Ruins', emoji:'🏛️'},
  desc:'You are an explorer in Pompeii... the day before Vesuvius erupts. Choose wisely.',
  skills:['History','Geography','Reading','Critical Thinking'], tags:['History','Geology','Dinosaurs'],
  source:{type:'video', videoId:'9klE-iUxX0c', provenance:'retrieved-description', transcriptNote:'TED-Ed lesson text verified 2026-09-04: Fabia/Lucius/Marcus, wedding, deafening boom, Vesuvius spews smoke/ash/rock, survive-the-disaster framing. Full captions not retrievable; questions limited to lesson-supported claims.'},
  media:{type:'youtube', youtubeId:'9klE-iUxX0c', channel:'TED-Ed'},
  predict:{type:'choice', q:'A whole Roman city vanished in ONE day, 2,000 years ago. What could bury an entire city?',
    options:['🌋 A volcano','🌊 A giant wave','🏜️ A sandstorm','👻 Ghosts']},
  video:{title:'Run, sail, or hide? How to survive the destruction of Pompeii — TED-Ed', duration:'5:30', chapters:['Market day','The mountain wakes','Run, sail, or hide?'],
    script:'Fabia, Lucius and Marcus are shopping in Pompeii when Vesuvius wakes with a deafening boom. Smoke, ash and rock rain down. Three siblings, three escape plans — run, sail, or hide. Which would YOU choose?'},
  story:{start:'market',
    nodes:{
      market:{text:'Pompeii, year 79. The market buzzes — bread, fish, oil lamps. Mount Vesuvius looms green and quiet. Too quiet? The ground trembled twice this week. A sailor offers you a boat ride out TONIGHT.', choices:[{t:'⛵ Take the boat tonight', to:'boat'},{t:'🏺 Stay and explore one more day', to:'forum'}]},
      boat:{text:'You sail out at sunset. At dawn the sky behind you turns BLACK. Vesuvius explodes — ash, fire, lightning. From the sea you watch, safe, and sketch everything. Your notes will teach the world.', choices:[{t:'📝 Write down everything you see', to:'ending1'}]},
      forum:{text:'Morning in the forum. A shiny shaking — plates rattle. A Pliny-like scholar shouts: “The mountain breathes smoke!” People laugh... then the ground ROARS. Ash falls like snow.', choices:[{t:'🏃 Run for the harbor!', to:'harbor'},{t:'📦 Help carry water to the frightened', to:'ending2'}]},
      harbor:{text:'You sprint through falling ash, scarf over your mouth — smart! Boats push off through floating pumice. Behind you, a dark cloud races down the mountain. You dive aboard the last boat.', choices:[{t:'🙏 Pull others aboard too', to:'ending3'}]},
      ending1:{end:true, text:'Your sketches survive 2,000 years. Historians call people like you the reason we KNOW Pompeii’s story. Observation saved the day!'},
      ending2:{end:true, text:'You help three families reach shelter before fleeing yourself. Pompeii is buried — but kindness is remembered. Archaeologists later find your water jar by the gate!'},
      ending3:{end:true, text:'You haul six people aboard! The cloud swallows the city behind you. Because you acted fast AND kindly, seven people see tomorrow.'}
    }},
  questions:[
    {kind:'mc', q:'Which volcano buried Pompeii?', options:['Etna','Vesuvius','Krakatoa','Fuji'], answer:1, why:'Mount Vesuvius, in the year 79!', source:'video', sourceConcept:'Vesuvius', sourceProvenance:'retrieved-description', sourceExcerpt:'TED-Ed lesson: the siblings “watch Vesuvius spew smoke, ash, and rock.”'},
    {kind:'tf', q:'True or false: Pompeii was buried by slow lava flows.', options:['True','False'], answer:1, why:'False! Smoke, ash and rock rained down — fast and deadly.', source:'video', sourceConcept:'burial by ash', sourceProvenance:'retrieved-description', sourceExcerpt:'TED-Ed lesson: “They watch Vesuvius spew smoke, ash, and rock.”'},
    {kind:'mc', q:'In the story, what interrupts the wedding talk in the market?', options:['A parade','A deafening boom from the mountain','A rainstorm','A lost dog'], answer:1, why:'A deafening boom — Vesuvius waking up!', source:'video', sourceConcept:'eruption moment', sourceProvenance:'retrieved-description', sourceExcerpt:'TED-Ed lesson: “a deafening boom interrupts them.”'}
  ],
  creative:{title:'A message from Pompeii', prompt:'You escape with one clay tablet. Write (or record) a 3-sentence message warning others or describing what you saw.', tabs:['text','voice','draw'],
    scout:'Chills! “The mountain breathed smoke” — you write like a true Roman witness. Historians would treasure this tablet.'},
  rabbitHoles:[
    {to:'volcano', why:'The mountain itself', bridge:'You survived the city. Now meet the mountain: what WAS that exploding peak, exactly?'},
    {to:'aqueducts', why:'How Romans actually lived', bridge:'Pompeii wasn’t just a disaster — it was a living Roman city with fountains, baths, and water on demand. How?!'},
    {to:'dino', why:'Other buried worlds', bridge:'Ash buried one city in a day. Rock buried a whole dinosaur world over millions of years.'}]},
{id:'islands', title:'How Do Islands Form?', theme:'earth', zone:'ocean', type:'discovery',
  emoji:'🏝️', grad:'linear-gradient(135deg,#6ee7b7,#0e7490)', duration:'9 min', xp:120, coins:30,
  collectible:{name:'Black Sand Vial', emoji:'⏳'}, worldItem:{name:'Coral Atoll', emoji:'🏝️'},
  desc:'Paradise built by fire! Watch volcanoes grow into islands, then ring into atolls.',
  skills:['Science','Geography'], tags:['Geology','Dinosaurs'],
  source:{type:'video', videoId:'01I8gH9ff0E', provenance:'retrieved-description', transcriptNote:'Publisher description verified 2026-09-04: volcanic islands — how they form and grow. Full transcript not retrievable; questions limited to description-supported claims.'},
  media:{type:'youtube', youtubeId:'01I8gH9ff0E', channel:'Explore Planet English'},
  predict:{type:'choice', q:'Some islands were built by FIRE under the sea. How could fire possibly make a beach?',
    options:['Lava piles up until it pokes out','Fire melts the ocean','Giants stack rocks','It can’t — trick question!']},
  video:{title:'Volcanic Islands — Explore Planet English', duration:'4:50', chapters:['Underwater eruptions','Island rises','Islands grow'],
    script:'Some volcanoes erupt UNDER the sea. Lava piles up, cools, piles more — until it pokes above the waves: a new island! Coral grows around it, the volcano sinks away, and a ring-shaped atoll is left.'},
  questions:[
    {kind:'mc', q:'How does a volcanic island start?', options:['Sand blows together','Underwater eruptions pile up lava','Giants stack rocks','It floats up'], answer:1, why:'Underwater lava piles higher and higher until it breaks the surface!', source:'video', sourceConcept:'island formation', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: “we will learn about the volcanic islands… how volcanic islands form and grow.”'},
    {kind:'tf', q:'True or false: Lava piles up, cools, and piles more until a new island pokes above the waves.', options:['True','False'], answer:0, why:'True! Pile, cool, repeat — until the island pops out of the ocean!', source:'reading', sourceConcept:'pile-up mechanism', sourceProvenance:'retrieved-description', sourceExcerpt:'Scout’s note (exact reading Jackson saw): “Lava piles up, cools, piles more — until it pokes above the waves: a new island!”'},
    {kind:'short', q:'Name one way islands form (volcano, coral, or your own idea).', keywords:['volcano','lava','coral','erupt','atoll','magma'], why:'Yes! Volcanoes and coral are island-builders. Fire making beaches — amazing.', source:'general', sourceConcept:'formation paths', sourceProvenance:'retrieved-description', sourceExcerpt:'Open idea-share; evaluated on effort and vocabulary, not a single fact.'}
  ],
  creative:{title:'Invent an island', prompt:'Invent your own island! What is it called? Volcano island or coral island? What animals live there? Draw or describe it.', tabs:['draw','text','build'],
    scout:'A volcano island with coral beaches AND parrots?! I want to visit! You combined both island recipes perfectly.'},
  rabbitHoles:[
    {to:'volcano', why:'The fire below', bridge:'Islands rise from fire — but what IS that fire, and where does it come from?'},
    {to:'sharks', why:'Who swims around islands', bridge:'New island, new neighborhood. The first locals arrived 450 million years before the welcome party.'},
    {to:'mars', why:'Islands… in space?', bridge:'Islands rise from seas here. On Mars, volcanoes rise with no sea at all.'}]},
{id:'mars', title:'Could Humans Live on Mars?', theme:'space', zone:'space', type:'discovery',
  emoji:'🔴', grad:'linear-gradient(135deg,#fda4af,#7c2d12)', duration:'12 min', xp:150, coins:40,
  collectible:{name:'Mars Pebble', emoji:'🔴'}, worldItem:{name:'Launch Pad', emoji:'🚀'},
  desc:'Freezing deserts, pink skies, giant volcanoes. Could YOU live there?',
  skills:['Science','Math','Critical Thinking','Creativity'], tags:['Fighter Jets','Engineering','Cars'],
  source:{type:'video', videoId:'cf-JUz3gqdk', provenance:'retrieved-description', transcriptNote:'Publisher description verified 2026-09-04: Squeaks and Jessi make a travel plan + packing list to overcome Mars challenges (Boston Museum of Science). Full transcript not retrievable; specific numbers (Olympus height, sol length) removed from questions as unverified.'},
  media:{type:'youtube', youtubeId:'cf-JUz3gqdk', channel:'SciShow Kids'},
  predict:{type:'text', q:'Mars air is too thin to breathe and nights are freezing. What THREE things would YOUR Mars base need first?'},
  video:{title:'How Will Humans Live on Mars? — SciShow Kids', duration:'5:13', chapters:['Very different planet','Packing list','Dome cities'],
    script:'Mars is very different from Earth, so Squeaks and Jessi make a travel plan and a packing list! Air you can breathe, water to drink, food to eat, shelter from the cold — what would YOU pack first?'},
  questions:[
    {kind:'mc', q:'Why can’t humans just breathe on Mars?', options:['Too much oxygen','Air is way too thin','It smells bad','Too windy'], answer:1, why:'Mars air is far too thin — and not the air we breathe. Suits and domes needed!', source:'video', sourceConcept:'thin atmosphere', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: Mars “is very different from Earth”; the packing-list premise is breathable air.'},
    {kind:'mc', q:'Squeaks and Jessi pack for Mars. What MUST be on the list?', options:['Air, water, food, shelter','Only toys and snacks','Just a camera','Nothing — Mars is like home'], answer:0, why:'Air, water, food, shelter — the survival packing list!', source:'video', sourceConcept:'packing list', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: “they make a travel plan and packing list that will help them overcome the challenges of life on Mars!”'},
    {kind:'tf', q:'True or false: Mars is so much like Earth that settlers need no special plan.', options:['True','False'], answer:1, why:'False! Mars is very different — that is the whole reason for the travel plan.', source:'video', sourceConcept:'Mars vs Earth', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: “our neighboring planet is very different from Earth.”'},
    {kind:'short', q:'Name ONE thing a Mars base needs and WHY.', keywords:['air','oxygen','water','food','heat','dome','suit','shield','radiation'], why:'Essential pick! Every Mars base starts with exactly that problem.', source:'general', sourceConcept:'survival needs', sourceProvenance:'retrieved-description', sourceExcerpt:'Open packing-list reasoning; evaluated on justification, not a single fact.'}
  ],
  creative:{title:'Design a Mars base', prompt:'Design your Mars base! Where does air, water, and food come from? What does it look like? Draw or describe it.', tabs:['draw','text','build'],
    scout:'Underground water tanks AND a veggie dome? NASA engineers think exactly like you. Your Mars crew would survive!'},
  rabbitHoles:[
    {to:'jets', why:'Flying with thin air', bridge:'Mars air is too thin for jet wings. So… what COULD fly there? Start with how wings work here.'},
    {to:'volcano', why:'Olympus Mons!', bridge:'The biggest volcano anywhere isn’t on Earth. It’s waiting on Mars — three Everests tall.'},
    {to:'car', why:'Rovers are space cars', bridge:'No roads, no gas stations, freezing dust. The coolest cars ever built drive on Mars.'}]},
{id:'sharks', title:'How Do Sharks Find Hidden Fish?', theme:'ocean', zone:'ocean', type:'discovery',
  emoji:'🦈', grad:'linear-gradient(135deg,#7dd3fc,#0c4a6e)', duration:'9 min', xp:120, coins:30,
  collectible:{name:'Shark Tooth', emoji:'🦷'}, worldItem:{name:'Reef Sanctuary', emoji:'🪸'},
  desc:'A sixth sense for hunting! Discover the electric spots on a shark’s face.',
  skills:['Science','Reading'], tags:['Dinosaurs','Geology'],
  source:{type:'video', videoId:'my4_gpefD7w', provenance:'retrieved-description', transcriptNote:'Publisher description verified 2026-09-04: special spots on a shark’s face help find food using electricity. Full transcript not retrievable; teeth-row and deep-time claims removed as unverified in this video.'},
  media:{type:'youtube', youtubeId:'my4_gpefD7w', channel:'SciShow Kids'},
  predict:{type:'choice', q:'Sharks can find fish hiding in the dark, buried in sand. What super-sense could find a hidden fish?',
    options:['⚡ Feeling tiny electricity','👁️ Seeing through sand','👃 Smelling colors','👂 Hearing whispers']},
  video:{title:'How Sharks Find Food With Electricity! — SciShow Kids', duration:'4:46', chapters:['Face spots','Hidden fish','Electric sense'],
    script:'Sharks have special spots on their faces that sense electricity! Hidden fish give off tiny electric signals — the shark feels them and snacks. An amazing animal super-sense!'},
  questions:[
    {kind:'mc', q:'Where are the shark’s electricity-sensing spots?', options:['On its tail','Special spots on its face','Inside its stomach','On its teeth'], answer:1, why:'Special spots on the face — a built-in fish-finder!', source:'video', sourceConcept:'face spots', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: “special spots on a shark’s face that help them find food using electricity!”'},
    {kind:'short', q:'Why would sensing electricity help a shark catch dinner?', keywords:['hidden','hide','find','dark','sand','sense','feel','electric'], why:'Exactly — hidden fish can’t hide their electricity!', source:'video', sourceConcept:'hunting use', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: spots “help them find food using electricity.”'},
    {kind:'img', q:'Which super-sense helps sharks find hidden fish?', options:[{e:'👁️',t:'Super eyesight'},{e:'⚡',t:'Electric-field sensing'},{e:'👃',t:'Smelling colors'}], answer:1, why:'They feel the tiny electricity that living muscles make — like a sixth sense!', source:'video', sourceConcept:'electroreception', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: sharks “find food using electricity.”'}
  ],
  creative:{title:'Best-adapted animal challenge', prompt:'A new animal must survive in the deep dark ocean. Which THREE superpowers (from sharks or your imagination) would you give it, and why?', tabs:['text','draw','voice'],
    scout:'Electric sensing PLUS conveyor teeth PLUS glow-in-the-dark? That creature rules the deep sea. Superb adapting!'},
  rabbitHoles:[
    {to:'dino', why:'Sharks met dinosaurs!', bridge:'Sharks swam with sea monsters for 200 million years. Then one bad day ended the giants — but not the sharks.'},
    {to:'islands', why:'Reefs and atolls', bridge:'Sharks patrol coral cities. Those cities grew on drowned volcanoes — want to see one?'},
    {to:'volcano', why:'Underwater fire vents', bridge:'Some sharks swim near underwater volcanoes. Fire below, teeth above.'}]},
{id:'car', title:'How Does a Car Engine Work?', theme:'engineering', zone:'engineering', type:'discovery',
  emoji:'🏎️', grad:'linear-gradient(135deg,#fca5a5,#7c2d12)', duration:'10 min', xp:130, coins:35,
  collectible:{name:'Piston Charm', emoji:'⚙️'}, worldItem:{name:'Turbo Garage', emoji:'🏎️'},
  desc:'Tiny explosions, 100 times a second, push you down the highway!',
  skills:['Science','Math','Critical Thinking'], tags:['Cars','Engineering','Fighter Jets'],
  source:{type:'video', videoId:'JfOMZfxH4ME', provenance:'retrieved-description', transcriptNote:'KLT “Car Engine Song” verified 2026-09-04 (2:08). Full lyrics/transcript not retrievable; questions limited to the engine-basics premise + standard four-stroke cycle (labeled reading/general).'},
  media:{type:'youtube', youtubeId:'JfOMZfxH4ME', channel:'KLT'},
  predict:{type:'choice', q:'Gasoline explodes 100 times a second inside a car — so why doesn’t the car blow up?',
    options:['Tiny explosions push parts, not the car','It actually does blow up','Cars are magic','Nobody knows']},
  video:{title:'How Does YOUR Car’s Engine Work?! — KLT', duration:'2:08', chapters:['Tiny explosions','Pistons pump','Vroom!'],
    script:'A car engine runs on tiny explosions! Fuel and air mix, get squeezed, SPARK — bang! The blast shoves parts called pistons down, and the pistons spin the wheels. Suck, squeeze, bang, blow — 100 times a second!'},
  questions:[
    {kind:'mc', q:'What pushes a gas car’s pistons?', options:['Tiny controlled explosions','Rubber bands','Wind','Hamsters'], answer:0, why:'Mini-explosions of fuel! That is the whole idea of the song.', source:'video', sourceConcept:'combustion', sourceProvenance:'retrieved-description', sourceExcerpt:'Video premise (title): “How Does YOUR Car’s Engine Work?!” — an engine song about explosions moving pistons.'},
    {kind:'sort', q:'Put the engine’s four steps in order:', options:['Suck fuel and air in','Squeeze the mix tight','SPARK — bang!','Blow the leftovers out'], answer:[0,1,2,3], why:'Suck, squeeze, bang, blow — the four-stroke party!', source:'reading', sourceConcept:'four-stroke order', sourceProvenance:'retrieved-description', sourceExcerpt:'Scout’s note (exact reading Jackson saw): “Suck, squeeze, bang, blow — 100 times a second!”'},
    {kind:'short', q:'Gas or electric: which would YOU pick for a race car, and why?', keywords:['gas','electric','fast','power','battery','explosion','motor','torque'], why:'Great reasoning! Real engineers argue about exactly that trade-off.', source:'general', sourceConcept:'engineering tradeoffs', sourceProvenance:'retrieved-description', sourceExcerpt:'Open opinion; evaluated on reasoning, not a single fact.'}
  ],
  creative:{title:'Invent a machine', prompt:'Invent a vehicle of the future! What powers it — explosions, batteries, rockets, something new? Draw or describe it.', tabs:['draw','text','build'],
    scout:'A solar-rocket skate-car?! Wild AND thought-through — you even solved refueling. Future inventor confirmed.'},
  rabbitHoles:[
    {to:'jets', why:'Engines that fly', bridge:'Car engines push wheels. Bolt wings on that idea and the road disappears beneath you.'},
    {to:'mars', why:'Rovers: cars on Mars', bridge:'The toughest cars ever built have six wheels, no driver, and drive on another planet.'},
    {to:'bridges', why:'Roads need bridges', bridge:'Every road ends at a river eventually. What holds the road up over the water?'}]},
{id:'aqueducts', title:'How Did Romans Move Water?', theme:'history', zone:'history', type:'challenge',
  emoji:'🏺', grad:'linear-gradient(135deg,#fde68a,#92400e)', duration:'10 min', xp:140, coins:35,
  collectible:{name:'Aqua Drop', emoji:'💧'}, worldItem:{name:'Aqua Bridge', emoji:'⛲'},
  desc:'No pumps, no engines — yet Romans moved rivers across valleys. How?!',
  skills:['History','Science','Math','Critical Thinking'], tags:['History','Engineering','Minecraft'],
  source:{type:'video', videoId:'tj-4WeOXKco', provenance:'retrieved-description', transcriptNote:'Full publisher description verified 2026-09-04: gravity downhill flow, channels/tunnels/arches, drinking/bathing/fountains/toilets, still standing. All questions cite it.'},
  media:{type:'youtube', youtubeId:'tj-4WeOXKco', channel:'Bedtime History'},
  predict:{type:'text', q:'Romans had NO pumps and NO engines. If YOUR town needed river water from 50 km away, how would you move it?'},
  video:{title:'Roman Aqueducts — Bedtime History', duration:'4:44', chapters:['No pumps?!','Gravity is the engine','The tiny slope trick'],
    script:'Romans had no pumps — so they used GRAVITY. Aqueducts slope downhill just a tiny bit — 1 meter every 2 km! Water flows for 50 km, over arched bridges across valleys, into city fountains. Roman engineers surveyed slopes with amazing precision.'},
  questions:[
    {kind:'mc', q:'What powered Roman aqueducts?', options:['Steam pumps','Gravity + a gentle downhill slope','Windmills','Slaves carrying buckets'], answer:1, why:'Gravity! A barely-visible slope carried water for miles.', source:'video', sourceConcept:'gravity flow', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: “aqueducts used gravity to move water downhill through channels, tunnels, and tall stone arches.”'},
    {kind:'tf', q:'True or false: Aqueduct channels sloped steeply downhill.', options:['True','False'], answer:1, why:'False! A gentle downhill slope — steep water would rush and break the channel.', source:'video', sourceConcept:'gentle gradient', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: “used gravity to move water downhill”; steep slopes would destroy the flow.'},
    {kind:'img', q:'Which Roman trick crossed a valley?', options:[{e:'🚇',t:'Tunnel under everything'},{e:'🌉',t:'Arched bridge carrying water'},{e:'🪣',t:'Bucket chain'}], answer:1, why:'Tall stone arches carried the water channel across valleys!', source:'video', sourceConcept:'arcade bridges', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: “tall stone arches” carried water to cities.'},
    {kind:'short', q:'The video says aqueduct water was used for drinking, bathing, fountains — even toilets! Which use surprises you most, and why?', keywords:['drink','bath','fountain','toilet','surpris','because','water'], why:'Great pick! Romans used running water for almost everything we do.', source:'video', sourceConcept:'water uses', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: “drinking, bathing, fountains, and even flushing toilets.”'}
  ],
  creative:{title:'Move water like a Roman', prompt:'Your LEGO town is on a hill and the “river” (a bowl) is across the room. How would you move water with NO pump? Draw or describe your aqueduct!', tabs:['draw','text','build'],
    scout:'A straw-aqueduct on books with a gentle slope — you literally rebuilt Roman engineering on your table. Brilliant!'},
  rabbitHoles:[
    {to:'pompeii', why:'Roman daily life', bridge:'Aqueducts fed the fountains and baths of Roman cities — including one city frozen in time by a volcano.'},
    {to:'bridges', why:'Arches everywhere', bridge:'Those water-bridges used the same arch trick as road bridges. Arches are EVERYWHERE once you see them.'},
    {to:'skyscraper', why:'Ancient → modern builders', bridge:'Romans stacked stone to the sky with arches. Modern builders stack steel — same dream, new bones.'}]},
{id:'fossils', title:'How Do Bones Turn to Stone?', theme:'dino', zone:'dino', type:'discovery',
  emoji:'🦴', grad:'linear-gradient(135deg,#d6c49a,#7c5a2d)', duration:'10 min', xp:130, coins:35,
  collectible:{name:'Ammonite Spiral', emoji:'🌀'}, worldItem:{name:'Bone Lab', emoji:'🔬'},
  desc:'A 12-year-old girl found sea monsters in a cliff. How do fossils form?',
  skills:['Science','History','Reading'], tags:['Dinosaurs','Geology'],
  source:{type:'video', videoId:'koota_lwU_4', provenance:'retrieved-description', transcriptNote:'Publisher description verified 2026-09-04: Mary Anning — without her we wouldn’t know nearly as much about dinosaurs. Full transcript not retrievable; fossil-formation mechanics labeled reading/general.'},
  media:{type:'youtube', youtubeId:'koota_lwU_4', channel:'SciShow Kids'},
  predict:{type:'choice', q:'Bones rot away in a few years. So how can a 200-million-year-old bone still exist?',
    options:['🪨 It turned to stone','❄️ It was frozen forever','🎨 Someone painted it','📦 It hid in a box']},
  video:{title:'Mary Anning: Fossil Hunter — SciShow Kids', duration:'4:13', chapters:['Cliff hunter','Sea monsters','Bones to stone'],
    script:'Mary Anning hunted fossils in English cliffs as a kid — and found giant sea reptiles nobody had ever seen! When animals get buried fast in mud, minerals slowly replace bone with stone. A fossil is nature’s statue.'},
  questions:[
    {kind:'mc', q:'Who helped us learn about dinosaurs?', options:['Mary Anning, a fossil hunter','A movie director','A pirate','Nobody — we guessed'], answer:0, why:'Mary Anning! Without her cliff discoveries we would know far less about dinosaurs.', source:'video', sourceConcept:'Mary Anning', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: “we wouldn’t know nearly as much as we do if it weren’t for a person named Mary Anning.”'},
    {kind:'mc', q:'What is a fossil?', options:['A painted rock','An animal or plant turned to stone','A type of volcano','A treasure chest'], answer:1, why:'Minerals replace bone bit by bit until the shape is stone — nature’s statue!', source:'reading', sourceConcept:'fossil definition', sourceProvenance:'retrieved-description', sourceExcerpt:'Scout’s note (exact reading Jackson saw): “minerals slowly replace bone with stone. A fossil is nature’s statue.”'},
    {kind:'short', q:'Why do fossils form in mud and rock — but not in a jungle?', keywords:['bury','mud','rot','protect','minerals','stone','quick'], why:'Exactly! Quick burial protects remains from rot while minerals do their slow magic.', source:'general', sourceConcept:'fossilization reasoning', sourceProvenance:'retrieved-description', sourceExcerpt:'Reasoning from Scout’s note about fast burial (evaluative, no new facts).'}
  ],
  creative:{title:'Leave a fossil', prompt:'If YOU became a fossil, what would future scientists learn? Draw the fossil you would leave behind!', tabs:['draw','text','voice'],
    scout:'A fossilized skateboard next to sneaker-prints?! Future scientists will be SO confused — and delighted.'},
  rabbitHoles:[
    {to:'dino', why:'The giants they came from…', bridge:'Fossils are how we KNOW dinosaurs. Ready to meet the giants themselves — and solve their disappearance?'},
    {to:'earth-core', why:'Digging deeper…', bridge:'Fossils sit in rock layers. But what is UNDER all those layers — all the way down?'},
    {to:'volcano', why:'Ash makes great fossils', bridge:'The fastest burier of all? Volcanic ash. It preserves everything — even whole cities.'}]},
{id:'earth-core', title:"What's Hiding Inside the Earth?", theme:'earth', zone:'earth', type:'discovery',
  emoji:'🌍', grad:'linear-gradient(135deg,#fbbf24,#7c2d12)', duration:'10 min', xp:135, coins:35,
  collectible:{name:'Core Crystal', emoji:'🔮'}, worldItem:{name:'Deep Drill', emoji:'🛠️'},
  desc:'Nobody has dug deeper than 12 km. So how do we know what is down there?',
  skills:['Science','Geography','Critical Thinking'], tags:['Geology','Dinosaurs'],
  source:{type:'video', videoId:'eXiVGEEPQ6c', provenance:'retrieved-description', transcriptNote:'Publisher description verified 2026-09-04: Earth has THREE distinct layers (crust, mantle, core), each with distinct properties. Four-layer split removed to match the video.'},
  media:{type:'youtube', youtubeId:'eXiVGEEPQ6c', channel:'Peekaboo Kidz'},
  predict:{type:'choice', q:'Nobody has EVER been deeper than 12 km underground. So how could anyone know what is at Earth’s center?',
    options:['🔊 Earthquake echoes','🔮 Magic crystal ball','🐀 Trained moles','📖 Guessing from books']},
  video:{title:'Structure Of The Earth — Dr. Binocs Show', duration:'3:13', chapters:['Crack the planet','Three layers','The metal heart'],
    script:'Dr. Binocs cracks Earth open: THREE distinct layers! The crust we live on, the thick rocky mantle, and the metal core at the center — each with its own superpowers.'},
  questions:[
    {kind:'sort', q:'Order the layers from outside to inside:', options:['Crust','Mantle','Core'], answer:[0,1,2], why:'Crust we stand on, thick rocky mantle, metal core heart!', source:'video', sourceConcept:'three layers', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: “our planet Earth is made up of three distinct layers… each of these layers have their own distinct properties.”'},
    {kind:'mc', q:'Which layer do we live on?', options:['Mantle','Core','Crust','None — we float'], answer:2, why:'The crust — Earth’s thin outer skin!', source:'video', sourceConcept:'crust', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: three distinct layers; the outermost is the crust we live on.'},
    {kind:'short', q:'Nobody can dig to the center. How could Dr. Binocs still know what is inside?', keywords:['waves','earthquake','echo','sound','shake','science','guess','study'], why:'Great thinking! Scientists read earthquake echoes like an X-ray of the planet.', source:'general', sourceConcept:'how we know', sourceProvenance:'retrieved-description', sourceExcerpt:'Open reasoning; the video’s whole premise is knowing the unseen inside.'}
  ],
  creative:{title:'Build planet Earth', prompt:'Make an Earth model: crust skin, mantle middle, metal heart. Draw it, build it from clay or LEGO, or describe your layers!', tabs:['draw','build','text'],
    scout:'A peach-planet with a metal pit?! That is EXACTLY how scientists picture it. Delicious AND correct.'},
  rabbitHoles:[
    {to:'volcano', why:'Lava comes from down there…', bridge:'That melted rock has to come from somewhere. Follow the lava elevator DOWN.'},
    {to:'supervolcano', why:'When the deep wakes up', bridge:'Sometimes the deep Earth doesn’t just ooze — it rearranges the map.'},
    {to:'mars', why:'Other planets, other insides', bridge:'Earth has a metal heart. What beats inside Mars?'}]},
{id:'birds', title:'How Do Birds Fly Without Engines?', theme:'engineering', zone:'engineering', type:'discovery',
  emoji:'🐦', grad:'linear-gradient(135deg,#a5f3c0,#047857)', duration:'9 min', xp:125, coins:30,
  collectible:{name:'Lucky Feather', emoji:'🪶'}, worldItem:{name:'Sky Nest', emoji:'🪹'},
  desc:'No engines, no fuel — just feathers. How do wings really work?',
  skills:['Science','Reading','Creativity'], tags:['Fighter Jets','Dinosaurs'],
  source:{type:'video', videoId:'4Bp4MgmT0Co', provenance:'retrieved-description', transcriptNote:'Publisher description + chapter list verified 2026-09-04: kinds of wings (bees to birds), how they help animals fly; chapters include How Bees Fly, How Penguins Fly. Dino-ancestry claim removed as unverified in this video.'},
  media:{type:'youtube', youtubeId:'4Bp4MgmT0Co', channel:'SciShow Kids'},
  predict:{type:'choice', q:'Birds are dinosaurs that learned to fly — with zero engines. What pushes a bird UP?',
    options:['🌀 Air pushing on wings','💪 Flapping really hard only','🎈 Birds are full of air','🪂 They just fall slowly']},
  video:{title:'How Do Animal Wings Work? — SciShow Kids', duration:'4:48', chapters:['Wing kinds','How bees fly','How penguins fly'],
    script:'From bees to birds to penguins — Mr. Brown shows Squeaks how different wings solve flying differently! Flap fast, glide far, or “fly” underwater: every wing is an engineering answer.'},
  questions:[
    {kind:'mc', q:'What pushes a bird upward?', options:['Magic feathers','Air pushing back on the wing','Wind from behind','Hollow bones alone'], answer:1, why:'Wings push air — air pushes back. That is how animals fly!', source:'video', sourceConcept:'how animals fly', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: “different kinds of wings and how they help animals, from bees to birds, fly!”'},
    {kind:'mc', q:'Bees have TINY wings. How do they stay up?', options:['They flap super fast','They never actually fly','They ride the wind only','They hold their breath'], answer:0, why:'Tiny wings flap incredibly fast — the video has a whole chapter on bee flight!', source:'video', sourceConcept:'bee flight', sourceProvenance:'retrieved-description', sourceExcerpt:'Video chapter list includes “How Bees Fly.”'},
    {kind:'img', q:'Penguins “fly” somewhere unusual. Where?', options:[{e:'🌊',t:'Underwater'},{e:'☁️',t:'Above clouds'},{e:'🌙',t:'To the Moon'}], answer:0, why:'Penguins fly with their flippers — underwater! Wings work in water too.', source:'video', sourceConcept:'penguin flight', sourceProvenance:'retrieved-description', sourceExcerpt:'Video chapter list includes “How Penguins Fly.”'}
  ],
  creative:{title:'Design a bird-plane', prompt:'Invent a flying machine that steals THREE ideas from birds. What bird parts does it use? Draw or describe it!', tabs:['draw','text','build'],
    scout:'Owl-silent wings AND eagle gliders AND hummingbird hover?! Nature’s R&D department approves!'},
  rabbitHoles:[
    {to:'jets', why:'Jets copied birds', bridge:'Now you know the original. See how humans bolted engines onto the same trick.'},
    {to:'dino', why:'Could birds be living dinosaurs?', bridge:'Some scientists say every pigeon is a dinosaur. Want to meet the giant cousins and decide?'},
    {to:'mars', why:'Flying on Mars?', bridge:'Birds need thick air. Mars barely has any — so what wings would work there?'}]},
{id:'forces', title:'What Is a Force, Anyway?', theme:'engineering', zone:'engineering', type:'discovery',
  emoji:'🧲', grad:'linear-gradient(135deg,#c4b5fd,#5b21b6)', duration:'9 min', xp:125, coins:30,
  collectible:{name:'Push-Pull Badge', emoji:'🏅'}, worldItem:{name:'Force Lab', emoji:'🧪'},
  desc:'Every push, pull, and crash in the universe — explained with toys!',
  skills:['Science','Math','Critical Thinking'], tags:['Engineering','Minecraft','Cars'],
  source:{type:'video', videoId:'ZLDUrPaLQWE', provenance:'retrieved-description', transcriptNote:'Publisher description verified 2026-09-04: push and pull — forces that start/stop/change-direction motion, everyday examples. All questions cite it.'},
  media:{type:'youtube', youtubeId:'ZLDUrPaLQWE', channel:'Homeschool Pop'},
  predict:{type:'choice', q:'You push a toy car. It rolls… then stops all by itself. What stopped it?',
    options:['🛑 Friction + air pushing back','👻 A ghost','🔋 It ran out of push-juice','🛑 The floor ate it']},
  video:{title:'Push and Pull for Kids — Homeschool Pop', duration:'5:28', chapters:['Push vs pull','Start, stop, turn','Forces everywhere'],
    script:'A force is a push or a pull! Pushes move things away, pulls bring them closer. Forces start motion, stop motion, and change direction — from toy cars to tug-of-war to gravity holding YOU down right now.'},
  questions:[
    {kind:'mc', q:'What is a force?', options:['A push or a pull','A type of car','A loud noise','A magic spell'], answer:0, why:'Every move anything ever makes starts with a push or a pull!', source:'video', sourceConcept:'force definition', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: “push and pull, two basic types of forces that affect how objects move!”'},
    {kind:'tf', q:'True or false: Forces can ONLY push, never pull.', options:['True','False'], answer:1, why:'False! Pushes AND pulls — the video is literally called Push AND Pull!', source:'video', sourceConcept:'push vs pull', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: “two basic types of forces” — push and pull.'},
    {kind:'img', q:'Which picture shows a PULL?', options:[{e:'⚽',t:'Kicking a ball'},{e:'🪢',t:'Tug-of-war rope'},{e:'🎳',t:'Bowling throw'}], answer:1, why:'Tug-of-war pulls toward you. Kicks and throws push away!', source:'video', sourceConcept:'identify pull', sourceProvenance:'retrieved-description', sourceExcerpt:'Publisher description: forces “start motion, stop motion, or change the direction” — pulls draw things closer.'}
  ],
  creative:{title:'Chain-reaction machine', prompt:'Design a 3-step push-and-pull chain reaction (like dominoes meets mousetrap). What pushes what? Draw or describe it!', tabs:['draw','text','build'],
    scout:'A rolling ball pulls a string that pushes a lever?! A beautiful force relay — engineers chain forces exactly like this.'},
  rabbitHoles:[
    {to:'bridges', why:'Forces holding up cars', bridge:'Bridges are force-juggling champions: pushes, pulls, and 1,000 cars at once.'},
    {to:'car', why:'Pushing 2 tons of car', bridge:'What happens when tiny explosions become pushes big enough to move a whole car?'},
    {to:'jets', why:'Pushing through the sky', bridge:'Cars push roads. Jets push AIR. Same forces, wilder ride.'}]},
{id:'mathbattle', title:'Minecraft Math: Mob Battle', theme:'minecraft', zone:'minecraft', type:'game',
  emoji:'⚔️', grad:'linear-gradient(135deg,#86efac,#14532d)', duration:'8 min', xp:120, coins:50,
  collectible:{name:'Diamond Shard', emoji:'💎'}, worldItem:{name:'Blocky Arena', emoji:'🏟️'},
  desc:'Monsters guard the diamond cave! Your sword is MATH. Defeat 5 mobs!',
  skills:['Math','Critical Thinking'], tags:['Minecraft','Cars'],
  source:{type:'game', videoId:null, provenance:'demo', transcriptNote:'Game mission: questions are generated live by the math engine, no static Q&A to audit.'},
  media:{type:'mock'},
  video:null, questions:[],
  creative:{title:'Victory blueprint', prompt:'You won! Describe (or draw) the ultimate weapon or trap you would build with your loot.', tabs:['text','draw'],
    scout:'A diamond sword with a lava trap moat? The mobs stand no chance. Master builder AND math warrior!'},
  rabbitHoles:[
    {to:'bridges', why:'Build with your loot', bridge:'Victory loot, meet engineering: the strongest structures ever built started as blocks.'},
    {to:'forces', why:'The physics of traps', bridge:'Your lava moat runs on forces and flows. Master the pushes and pulls behind it.'},
    {to:'car', why:'Minecart engineering', bridge:'Redstone, rails, powered carts — Minecraft’s machines run on the same ideas as real engines.'}]},
{id:'supervolcano', title:'Supervolcanoes: Bigger Than Mountains?', theme:'earth', zone:'earth', type:'discovery', lockedByDefault:true,
  emoji:'💥', grad:'linear-gradient(135deg,#f0abfc,#7e22ce)', duration:'9 min', xp:130, coins:35,
  collectible:{name:'Ash Crystal', emoji:'💠'}, worldItem:{name:'Caldera Lake', emoji:'🏞️'},
  desc:'Some volcanoes don’t have peaks — because they BLEW themselves away!',
  skills:['Science','Geography'], tags:['Geology','Dinosaurs'],
  source:{type:'mock', videoId:null, provenance:'mock-script', transcriptNote:'No video attached (mock fallback mission). Questions are general-knowledge, internally consistent, explicitly labeled.'},
  media:{type:'mock'},
  predict:{type:'text', q:'What if a volcano was SO big you could stand inside it and not even know? What would that look like?'},
  video:{title:'When Earth Sneezes', duration:'3:20', chapters:['No mountain?','Yellowstone sleeps','Ash worldwide'],
    script:'Supervolcanoes are so huge you can stand inside one and not know! Yellowstone is a 70-km-wide hidden crater. Its last big eruption spread ash across half a continent. Scientists watch it closely — it is sleeping, not extinct.'},
  questions:[
    {kind:'mc', q:'Why can’t you see a supervolcano’s mountain?', options:['It is invisible','It blew itself apart, leaving a giant dip (caldera)','It hides underwater always','It is on Mars'], answer:1, why:'It exploded so hard the mountain collapsed into a giant bowl called a caldera!', source:'general', sourceConcept:'caldera', sourceProvenance:'mock-script', sourceExcerpt:'Mock-lesson general knowledge (no video attached).'},
    {kind:'tf', q:'True or false: Yellowstone is being watched by scientists.', options:['True','False'], answer:0, why:'True! Sensors track every wiggle — it is asleep, and scientists keep watch.', source:'general', sourceConcept:'monitoring', sourceProvenance:'mock-script', sourceExcerpt:'Mock-lesson general knowledge (no video attached).'}
  ],
  creative:{title:'Caldera diorama plan', prompt:'Describe or draw a supervolcano caldera: the dip, the lake inside, and where the ash went!', tabs:['draw','text'],
    scout:'A lake inside the crater with ash arrows across the map — that is exactly how scientists draw it. Stunning!'},
  rabbitHoles:[
    {to:'volcano', why:'Back to basics', bridge:'Supersized is fun — but the same small rules drive every eruption. Revisit the basics.'},
    {to:'pompeii', why:'Famous eruption', bridge:'One famous morning, one buried city. The human-scale version of the monster.'},
    {to:'mars', why:'Bigger on Mars', bridge:'Thought Yellowstone was big? Olympus Mons laughs at Yellowstone.'}]},
];

const JOURNEYS = [
  {name:'The Builder Path', emoji:'🧱', steps:['mathbattle','bridges','forces','skyscraper','aqueducts','pompeii']},
  {name:'The Sky Path', emoji:'✈️', steps:['jets','birds','mars','car']},
  {name:'The Deep-Time Path', emoji:'🦴', steps:['dino','fossils','earth-core','volcano','pompeii','islands','sharks']},
];

const SEED_APPROVALS = [
  {id:'ap1', title:'How Do Tornadoes Form?', emoji:'🌪️', grad:'linear-gradient(135deg,#a5b4fc,#0f766e)', duration:'4:10', reason:'Follows the volcano + forces rabbit hole', status:'pending'},
  {id:'ap2', title:'The Roman Army: Engineering an Empire', emoji:'🛡️', grad:'linear-gradient(135deg,#fcd34d,#7c2d12)', duration:'5:02', reason:'Connects Pompeii → Ancient Rome journey', status:'pending'},
  {id:'ap3', title:'Fossil Hunting 101', emoji:'🦴', grad:'linear-gradient(135deg,#fde68a,#92400e)', duration:'3:48', reason:'Jackson replayed the Dino mission twice', status:'pending'},
];

const LIBRARY = [
  {title:'The Water Cycle Adventure', emoji:'💧', subject:'Science', age:'6–8'},
  {title:'Fractions with Pizza Builders', emoji:'🍕', subject:'Math', age:'6–8'},
  {title:'Egypt: Pyramids & Mummies', emoji:'🏜️', subject:'History', age:'7–10'},
  {title:'Maps & Compasses', emoji:'🧭', subject:'Geography', age:'6–9'},
  {title:'Write Your Own Mystery', emoji:'🔍', subject:'Reading', age:'7–10'},
  {title:'Simple Machines Playground', emoji:'⚙️', subject:'Science', age:'6–8'},
  {title:'Money & Counting Coins', emoji:'🪙', subject:'Math', age:'5–7'},
  {title:'Oceans: Coral Cities', emoji:'🪸', subject:'Science', age:'6–10'},
];

const INTEREST_POOL = ['Minecraft','Cars','Fighter Jets','Dinosaurs','Space','Animals','Drawing','Sports','Machines','Engineering','Oceans','Mysteries','How Things Work','Strange Places'];
const INTEREST_EMOJI = {'Minecraft':'⛏️','Cars':'🏎️','Fighter Jets':'🛩️','Dinosaurs':'🦕','Space':'🚀','Animals':'🦁','Drawing':'🎨','Sports':'⚽','Machines':'⚙️','Engineering':'🌉','Oceans':'🌊','Mysteries':'🔍','How Things Work':'🔧','Strange Places':'🗺️'};
const GOAL_POOL = ['Math','Science','History','Geography','Reading','Writing','Creativity','Critical Thinking','Technology','Life Skills'];
const GOAL_EMOJI = {'Math':'🔢','Science':'🔬','History':'🏛️','Geography':'🗺️','Reading':'📖','Writing':'✏️','Creativity':'🎨','Critical Thinking':'🧠','Technology':'💻','Life Skills':'🌱'};

function defaultProfile(){
  return {
    name:'Jackson', age:6, avatar:'🦊', level:3, xp:320, coins:85,
    streak:4, streakDays:['M','T','W','T'],
    interests:{'Minecraft':95,'Cars':90,'Engineering':88,'Fighter Jets':82,'Dinosaurs':70},
    interestList:['Minecraft','Cars','Fighter Jets','Engineering','Dinosaurs'],
    goals:['Math','Science','History','Geography','Reading','Creativity'],
    skills:{'Reading':85,'Math':72,'Science':61,'Geography':44,'History':38,'Creativity':66,'Critical Thinking':58},
    prefs:{balance:55, challenge:60, independence:70},
    completedMissions:[], unlockedZones:['home','minecraft','dino','engineering','earth'],
    collectibles:[], worldItems:[{name:'Cozy Home Base', emoji:'🏠'}],
    minutes:47, topicsExplored:['Minecraft Builds','Bridges','Dino Bones'],
    pathTrail:[],
    sentMissions:[], approvals:JSON.parse(JSON.stringify(SEED_APPROVALS)),
    generatedCount:0, mathBest:0,
    stats:{bestDepth:0, chains:[], started:0, completed:0},
  };
}
